/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   zob_main.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sad-aude <sad-aude@student.42lyon.fr>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/02/15 18:53:09 by sad-aude          #+#    #+#             */
/*   Updated: 2020/05/02 16:33:51 by sad-aude         ###   ########lyon.fr   */
/*                                                                            */
/* ************************************************************************** */

#include "include/ft_printf.h"
#include <limits.h>

int     main()
{
    int fuck;

    fuck = 0;

    // dprintf(1, "TESTS TYPE D\n");
    // dprintf(1, "\n");
    // ft_printf("faux: %d\n", 123);
    // dprintf(1, "vrai: %d\n", 123);
    // dprintf(1, "\n");
    // ft_printf("faux: %d\n", 2147483647);
    // dprintf(1, "vrai: %d\n", 2147483647);
    // dprintf(1, "\n");
    // ft_printf("faux: %-d\n", 4294967295);
    // dprintf(1, "vrai: %-d\n", 4294967295);
    // dprintf(1, "\n");
    // ft_printf("faux: %10.4d\n", -2);
    // dprintf(1, "vrai: %10.4d\n", -2);
    // dprintf(1, "\n");
    // ft_printf("faux: %020.10d\n", -123456789);
    // dprintf(1, "vrai: %020.10d\n", -123456789);
    // dprintf(1, "\n");
    // ft_printf("faux : %-10.30d\n", 0123);
    // dprintf(1, "vrai : %-10.30d\n", 0123);
    // dprintf(1, "\n");
    // ft_printf("faux mix = %d coucou %*.*s\n", 15, 6, 3, "SALUT MEC");
    // dprintf(1, "vrai mix = %d coucou %*.*s\n", 15, 6, 3, "SALUT MEC");
    // dprintf(1, "\n");
    // dprintf(1, "vrai = %-20d\n", -2143648);
    // ft_printf("faux = %-20d\n", -2143648);
    // dprintf(1, "\n");
    // dprintf(1, "vrai = %010.2d\n", -2147);
    // ft_printf("faux = %010.2d\n", -2147);
    // dprintf(1, "\n");
	// ft_printf("faux : %d\n", 0);
    // dprintf(1, "vrai : %d\n", 0);
    // dprintf(1, "\n");
	// ft_printf("faux : %d\n", 2147483647);
    // dprintf(1, "vrai : %d\n", 2147483647);
    // dprintf(1, "\n");
	// ft_printf("faux : %.2d\n", -0);
    // dprintf(1, "vrai : %.2d\n", -0);
    // dprintf(1, "\n");
	// ft_printf("faux : %0*d\n", -10, 42);
    // dprintf(1, "vrai : %0*d\n", -10, 42);
    // dprintf(1, "\n");
	// ft_printf("faux : %-*d\n", -9, -87);
    // dprintf(1, "vrai : %-*d\n", -9, -87);
    // dprintf(1, "\n");
    // ft_printf("faux : %02i\n", -1);
    // dprintf(1, "vrai : %02i\n", -1);
    // dprintf(1, "\n");
	// ft_printf("faux : '%.0i\n", 2147483647);
    // dprintf(1, "vrai : '%.0i\n", 2147483647);
    // dprintf(1, "\n");
	// ft_printf("faux : ' %10.4i'\n", -01);
    // dprintf(1, "vrai : ' %10.4i'\n", -01);
    // dprintf(1, "\n");
    // ft_printf("faux : '%10.4i'\n", 111);
    // dprintf(1, "vrai : '%10.4i'\n", 111);
    // dprintf(1, "\n");
	// ft_printf("faux : '%-2i\n", 0);
    // dprintf(1, "vrai : '%-2i\n", 0);
    // dprintf(1, "\n");
	// ft_printf("faux : '%i\n", -1);
    // dprintf(1, "vrai : '%i\n", -1);
    // dprintf(1, "\n");
	// ft_printf("faux : '%-----10i\n", 0);
    // dprintf(1, "vrai : '%-----10i\n ", 0);
    // dprintf(1, "\n");
	// ft_printf("faux : '%010.*i\n", 15, -1);
    // dprintf(1, "vrai : '%010.*i\n", 15, -1);
    // dprintf(1, "\n");
	// ft_printf("faux : '%-15.10i\n", -1);
    // dprintf(1, "vrai : '%-15.10i\n", -1);
    // dprintf(1, "\n");
	// ft_printf("faux : '%010i\n", -1);
    // dprintf(1, "vrai : '%010i\n", -1);
    // dprintf(1, "\n");
	// ft_printf("faux : '%15.0i\n", 0);
    // dprintf(1, "vrai : '%15.0i\n", 0);
    // dprintf(1, "\n");
	// ft_printf("faux : '%01.1i\n", 0);
    // dprintf(1, "vrai : '%01.1i\n", 0);
    // dprintf(1, "\n");
	// ft_printf("faux : '%03.1i\n", 0);
    // dprintf(1, "vrai : '%03.1i\n", 0);
    // dprintf(1, "\n");
    // ft_printf("faux : '%.Oi\n", 0);
    // dprintf(1, "vrai : '%.0i\n", 0);
    // dprintf(1, "\n");
	// ft_printf("faux : '%.*i\n", -1, 0);
    // dprintf(1, "vrai : '%.*i\n", -1, 0);
    // dprintf(1, "\n");
	// ft_printf("faux : %03.0i\n", -1);
    // dprintf(1, "vrai : %03.0i\n", -1);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : |%d|\n", 0);
	// ft_printf("faux : |%d|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%08i|\n", -71);
	// ft_printf("faux : |%08i|\n", -71);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-7d|\n", 7789);
	// ft_printf("faux : |%-7d|\n", 7789);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%12.5d|\n", 140);
	// ft_printf("faux : |%12.5d|\n", 140);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%0010.4d|\n", 0);
	// ft_printf("faux : |%0010.4d|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%20.d et %.4i !|\n", 0x11ffaa147, (signed char)-8);
	// ft_printf("faux : |%20.d et %.4i !|\n", 0x11ffaa147, (signed char)-8);
    // dprintf(1, "\n");
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%d|\n", 534);
	// ft_printf("faux : |%d|\n", 534);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%.2i|\n", -10);
	// ft_printf("faux : |%.2i|\n", -10);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%0.23d|\n", -4440);
	// ft_printf("faux : |%0.23d|\n", -4440);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%i|\n", -4440);
	// ft_printf("faux : |%i|\n", -4440);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%d|\n", 25000);
	// ft_printf(" faux : |%d|\n", 25000);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-2i|\n", -7);
	// ft_printf("faux : |%-2i|\n", -7);
    // dprintf(1, "\n");
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%03i|\n", 0);
	// ft_printf("faux : |%03i|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%5d|\n", -741);
	// ft_printf("faux : |%5d|\n", -741);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%.d|\n", 0);
	// ft_printf("faux : |%.d|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%d|\n", 0);
	// ft_printf("faux : |%d|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%#o|\n", 0);
	// ft_printf("faux : |%#o|\n", 0);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : |%04d|\n", 0);
	// ft_printf("faux : |%04d|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-12i et |%--2.4s| |%24s| !|\n", 0, NULL, "coco");
	// ft_printf("faux : |%-12i et |%--2.4s| |%24s| !|\n", 0, NULL, "coco");
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-12d|\n", 0);
	// ft_printf("faux : |%-12d|\n", 0);
    // dprintf(1, "\n");

    // dprintf(1, "TESTS TYPE U\n");
    // dprintf(1, "\n");
    // dprintf(1, "vrai : |%u|\n", -100111);
	// ft_printf("faux : |%u|\n", -100111);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-3u|\n", 194);
    // ft_printf("faux : |%-3u|\n", 194);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-12u|\n", 17894);
    // ft_printf("faux : |%-12u|\n", 17894);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%u|\n", -12345612220);
	// ft_printf("faux : |%u|\n", -12345612220);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%u|\n", -127);
	// ft_printf("faux : |%u|\n", -127);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : |toto et %02u coco %-5u mimi|\n", 19, -20);
	// ft_printf("faux : |toto et %02u coco %-5u mimi|\n", 19, -20);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : |%--.4u|\n", -12);
    // ft_printf("faux : |%--.4u|\n", -12);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%u|\n", 0);
	// ft_printf("faux : |%u|\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%4u|\n", 1);
	// ft_printf("faux : |%4u|\n", 1);
    // dprintf(1, "\n");
	// ft_printf("faux : |%01.u| |%02.u| |%03.u| |%1.u| |%2.u| |%.1u| |%.2u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "vrai : |%01.u| |%02.u| |%03.u| |%1.u| |%2.u| |%.1u| |%.2u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "\n");
	// ft_printf("faux : |%01.u| |%02.u| |%03.u| |%1.u| |%2.u| |%.1u| |%.2u|\n", -40, -20, -4, -120, -578, -9, -8);
	// dprintf(1, "vrai : |%01.u| |%02.u| |%03.u| |%1.u| |%2.u| |%.1u| |%.2u|\n", -40, -20, -4, -120, -578, -9, -8);
	// dprintf(1, "\n");
	// ft_printf("faux : |%1.5u| |%1.u| |%-5.u| |%-5.3u| |%+3.u| |%-.5u| |%8.3u|\n", -4, -2, -4, -1, -5, -9, -8);
	// dprintf(1, "vrai : |%1.5u| |%1.u| |%-5.u| |%-5.3u| |%+3.u| |%-.5u| |%8.3u|\n", -4, -2, -4, -1, -5, -9, -8);
	// dprintf(1, "\n");
	// ft_printf("faux : |%01.u| |%02.u| |%03.u| |%1.u| |%2.u| |%.1u| |%.u|\n", 0, 0, 0, 0, 0, 0, 0);
	// dprintf(1, "vrai : |%01.u| |%02.u| |%03.u| |%1.u| |%2.u| |%.1u| |%.u|\n", 0, 0, 0, 0, 0, 0, 0);
	// dprintf(1, "\n");
	// ft_printf("faux : |%10.u| |%-10.u| |%10.u| |%10.u| |%-10.u| |%5.u| |%-5.u|\n", 0, 0, 0, 0, 0, 0, 0);
	// dprintf(1, "vrai : |%10.u| |%-10.u| |%10.u| |%10.u| |%-10.u| |%5.u| |%-5.u|\n", 0, 0, 0, 0, 0, 0, 0);
	// dprintf(1, "\n");
	// ft_printf("faux : |%1.u| |%2.u| |%3.u| |%1.u| |%2.u| |%.1u| |%.u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "vrai : |%1.u| |%2.u| |%3.u| |%1.u| |%2.u| |%.1u| |%.u|\n", 5, 5, 5, 5, 5, 5, 5);
	// printf("\n");
	// ft_printf("faux : |%-1.5u| |%+2.4u| |%-3.u| |%-1.u| |%-2.u| |%-3.1u| |%5.2u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "vrai : |%-1.5u| |%+2.4u| |%-3.u| |%-1.u| |%-2.u| |%-3.1u| |%5.2u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "\n");
	// ft_printf("faux : |%1.0u| |%2.1u| |%3.0u| |%1.1u| |%2.0u| |%1.1u| |%1.2u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "vrai : |%1.0u| |%2.1u| |%3.0u| |%1.1u| |%2.0u| |%1.1u| |%1.2u|\n", 5, 5, 5, 5, 5, 5, 5);
	// dprintf(1, "\n");
	// ft_printf("faux : |%1.1u| |%2.0u| |%3.1u| |%1.0u| |%2.1u| |%1.0u| |%0.2u|\n", 15, 300, 140, 9, 7, 15488, 203);
	// dprintf(1, "vrai : |%1.1u| |%2.0u| |%3.1u| |%1.0u| |%2.1u| |%1.0u| |%0.2u|\n", 15, 300, 140, 9, 7, 15488, 203);
	// dprintf(1, "\n");
	// ft_printf("faux : |%1u| |%.10u| |%10u| |%-10u| |%+10u| |%+10.u| |%-10.u|\n", -4, -2, -4, -1, -5, -9, -8);
	// dprintf(1, "vrai : |%1u| |%.10u| |%10u| |%-10u| |%+10u| |%+10.u| |%-10.u|\n", -4, -2, -4, -1, -5, -9, -8);
	// dprintf(1, "\n");
	// ft_printf("faux : |% .10lu| |%-.10u| |%+.10u| |% .10u| |%- .5u| |%+ .5u| |%+ .10u|\n", 4, 2, 4, 1, 5, 9, 8);
	// dprintf(1, "vrai : |% .10lu| |%-.10u| |%+.10u| |% .10u| |%- .5u| |%+ .5u| |%+ .10u|\n", 4, 2, 4, 1, 5, 9, 8);
	// dprintf(1, "\n");
	// ft_printf("faux : |%.10lu| |%-.10u| |%+.10u| |%.10u| |%-.5u| |%+.5u| |%+.10u|\n", 0, 0, 0, 0, 0, 0, 0);
	// dprintf(1, "vrai : |%.10lu| |%-.10u| |%+.10u| |%.10u| |%-.5u| |%+.5u| |%+.10u|\n", 0, 0, 0, 0, 0, 0, 0);
	// dprintf(1, "\n");
	// ft_printf("faux : |%10.lu| |%-10.u| |%10.u| |%10.u| |%-10.u| |%5.u| |%-5.u|\n", 4, 2, 4, 1, 5, 9, 8);
	// dprintf(1, "vrai : |%10.lu| |%-10.u| |%10.u| |%10.u| |%-10.u| |%5.u| |%-5.u|\n", 4, 2, 4, 1, 5, 9, 8);
	

    // dprintf(1, "TESTS TYPE S\n");
    // dprintf(1, "\n");
    // ft_printf("faux : [%.15s] salut\n", NULL);
    // dprintf(1, "vrai : [%.15s] salut\n", NULL);
    // dprintf(1, "\n");
    // ft_printf("[Faux] : hello %050.6s\n", "my name is Sam");
    // dprintf(1, "[Vrai] : hello %050.6s\n", "my name is Sam");
    // dprintf(1, "\n");
    // ft_printf("Faux : hello %20.s\n", "");
    // dprintf(1, "Vrai : hello %20.s\n", "");
    // dprintf(1, "\n");
    // ft_printf("Faux : hello %-10.3s\n", "my name is Sam");
    // dprintf(1, "Vrai : hello %-10.3s\n", "my name is Sam");
    // dprintf(1, "\n");
    // ft_printf( "faux : '%*s'\n", 3, "basique");
    // dprintf(1, "vrai : '%*s'\n", 3, "basique");
    // dprintf(1, "\n");
    // ft_printf( "faux : '%*s'\n", -10, "basique");
    // dprintf(1, "vrai : '%*s'\n", -10, "basique");
    // ft_printf("Faux segfault : %-10s ---- %10s\n", "lol", "mdr");
    // dprintf(1, "Vrai segfault : %-10s ---- %10s\n", "lol", "mdr");
    // dprintf(1, "\n");
    // ft_printf("Faux : %*s ---- %*s\n", -15, "lol", -15, "mdr");
    // dprintf(1, "Vrai : %*s ---- %*s\n", -15, "lol", -15, "mdr");
    // dprintf(1, "\n");
    // ft_printf("[Faux : %-010.5s] ---- %-10s\n", "lol", "mdr");
    // dprintf(1, "[Vrai : %-010.5s] ---- %-10s\n", "lol", "mdr");
    // dprintf(1, "\n");
    // ft_printf("faux :[%015.5s]\n", "12345678925262515615625614");
    // dprintf(1, "vrai :[%015.5s]\n", "12345678925262515615625614");
    // dprintf(1, "\n");
    // ft_printf("faux = %.*s\n", 6, "SALUT MEC");
    // dprintf(1, "vrai = %.*s\n", 6, "SALUT MEC");
    // dprintf(1, "\n");
    // ft_printf("faux = %*.*s\n", 15, 6, "SALUT MEC");
    // dprintf(1, "vrai = %*.*s\n", 15, 6, "SALUT MEC");
    // dprintf(1, "\n");
	// ft_printf("faux : '%10s'\n", NULL);
    // dprintf(1, "vrai : '%10s'\n", NULL);
	// ft_printf("faux : '%2s'\n", NULL);
    // dprintf(1, "vrai : '%2s'\n", NULL);
	// ft_printf("faux : '%-2s'\n", NULL);
    // dprintf(1, "vrai : '%-2s'\n", NULL);
	// ft_printf("faux : '%10.2s'\n", NULL);
    // dprintf(1, "vrai : '%10.2s'\n", NULL);
	// ft_printf("faux : '%-10s'\n", NULL);
    // dprintf(1, "vrai : '%-10s'\n", NULL);
	// ft_printf("faux : '%-10.5s'\n", NULL);
    // dprintf(1, "vrai : '%-10.5s'\n", NULL);
	// ft_printf("faux : '%-15s'\n", "basique");
    // dprintf(1, "vrai : '%-15s'\n", "basique");
    // dprintf(1, "\n");
    // dprintf(1, "\n");

    

    dprintf(1, "TESTS TYPE C\n");
    // dprintf(1, "\n");
	// printf("	#2	    ret    '%d' \n", printf("'%10c %4c'", 56, 111));
	// printf("	#3		ret    '%d' \n", printf("'%*c'", -4, 111));
	// printf("	#4	    ret    '%d' \n", printf("'%-10c'", 0));
	// printf("	#5	    ret    '%d' \n", printf("'%*c'", -10, 0));
	// dprintf(1, "\n");
	// ft_printf("	#2	    ret    '%d' \n", ft_printf("'%10c %4c'", 56, 111));
	// ft_printf("	#3		ret    '%d' \n", ft_printf("'%*c'", -4, 111));
	// ft_printf("	#4	    ret    '%d' \n", ft_printf("'%-10c'", 0));
	// ft_printf("	#5	    ret    '%d' \n", ft_printf("'%*c'", -10, 0));
	// dprintf(1, "\n");
    dprintf(1, "LE VRAI = %d\n", printf("oueche : %-19c%c%c%c\n", 'm', 'a', 'e', 'l'));
    dprintf(1, "LE FAUX = %d\n", ft_printf("oueche : %-19c%c%c%c\n", 'm', 'a', 'e', 'l'));
    dprintf(1, "\n");
    dprintf(1, "LE VRAI = %d\n", printf("%-10.3s\n", "mael"));
    dprintf(1, "LE FAUX = %d\n", ft_printf("%-10.3s\n", "mael"));
    dprintf(1, "\n");
    dprintf(1, "LE VRAI = %d\n", printf("%10d-%10d\n", 1234, 20));
    dprintf(1, "LE FAUX = %d\n", ft_printf("%10d-%10d\n", 1234, 20));
    dprintf(1, "\n");
    dprintf(1, "LE VRAI = %d\n", printf("%s\n", "mael"));
    dprintf(1, "LE FAUX = %d\n", ft_printf("%s\n", "mael"));
    dprintf(1, "\n");
    dprintf(1, "LE VRAI = %d\n", printf("%s\n", ""));
    dprintf(1, "LE FAUX = %d\n", ft_printf("%s\n", ""));
    dprintf(1, "\n");
    dprintf(1, "LE VRAI = %d\n", ft_printf("%'u", 1000));
    dprintf(1, "LE FAUX = %d\n", ft_printf("%'u", 1000));
    // dprintf(1, "vrai : %c\n", 'm');
    // ft_printf("faux : %c\n", 'm');
    // dprintf(1, "\n");
    // dprintf(1,"vrai : %10c %4c\n", 56, 111);
    // ft_printf("faux : %10c %4c\n", 56, 111);
    // dprintf(1, "\n");
	// dprintf(1,"vrai : %*c\n", -4, 111);
    // ft_printf("faux : %*c\n", -4, 111);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : %-10c\n", 0);
    // ft_printf("faux : %-10c\n", 0);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : %*c\n", -10, 0);
    // ft_printf("faux : %*c\n", -10, 0);
    // dprintf(1, "\n");
    // dprintf(1, "vrai : %*c\n", -4, 111);
    // ft_printf("faux : %*c\n", -4, 111);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : %-10c\n", 0);
    // ft_printf("faux : %-10c\n", 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : %*c\n", -10, 'b');
    // ft_printf("faux : %*c\n", -10, 'b');
    // dprintf(1, "\n");

    // dprintf(1, "TESTS TYPE %\n");
    // dprintf(1, "\n");
    // ft_printf("faux : [%%.15s] salut\n", NULL);
    // dprintf(1, "vrai : [%%.15s] salut\n", NULL);
    // dprintf(1, "\n");
    // ft_printf("[Faux] : hello %%050%%.6s\n", "my name is Sam");
    // dprintf(1, "[Vrai] : hello %%050%%.6s\n", "my name is Sam");
    // dprintf(1, "\n");
    // ft_printf("Faux : hello %%%%0004%20.s\n", "");
    // dprintf(1, "Vrai : hello %%%%0004%20.s\n", "");
    // dprintf(1, "\n");
    // ft_printf("faux : titi %---12.5% et%%%0004% et %1%\n");
    // dprintf(1, "vrai : titi %---12.5% et%%%0004% et %1%\n");
    // dprintf(1, "\n");
    // ft_printf("faux : %0005% et %1%\n");
    // dprintf(1, "vrai : %0005% et %1%\n");
    // dprintf(1, "\n");
    // ft_printf("faux : %%\n");
    // dprintf(1, "vrai : %%\n");
    // dprintf(1, "\n");
    // ft_printf("faux : %%%%\n");
    // dprintf(1, "vrai : %%%%\n");
    // dprintf(1, "\n");
    // ft_printf("faux : %c\n", '1');
    // dprintf(1, "vrai : %c\n", '1');
    // dprintf(1, "\n");
    // ft_printf("faux : %c\n", 256 + 48);
    // dprintf(1, "vrai : %c\n", 256 + 48);
    // dprintf(1, "\n");
    // ft_printf("faux : %c%%\n", '3');
    // dprintf(1, "vrai : %c%%\n", '3');
    // dprintf(1, "\n");
    // ft_printf("faux : %c%%\n", '129');
    // dprintf(1, "vrai : %c%%\n", '129');
    // dprintf(1, "\n");
    // ft_printf("faux : %c\n", -129);
    // dprintf(1, "vrai : %c\n", -129);
    // dprintf(1, "\n");
    // ft_printf("faux : %s%%\n", "Hello3");
    // dprintf(1, "vrai : %s%%\n", "Hello3");
    // dprintf(1, "\n");
    // ft_printf("faux : %u\n", UINT_MAX + 1);
    // dprintf(1, "vrai : %u\n", UINT_MAX + 1);
    // dprintf(1, "LE VRAI = %d\n", printf("try for percent = %10%\n"));
    // dprintf(1, "LE FAUX = %d\n", ft_printf("try for percent = %10%\n"));
    // dprintf(1, "\n");

    // dprintf(1, "TESTS TYPE xX\n");
    // dprintf(1, "\n");
    // dprintf(1, "vrai : |%20x|\n", 0x123456bc);
	// ft_printf("faux : |%20x|\n", 0x123456bc);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%0#10.0x %0#x|\n", 12345, 0);
	// ft_printf("faux : |%0#10.0x %0#x|\n", 12345, 0);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |%-6x|\n", 0xdd66);
	// ft_printf("faux : |%-6x|\n", 0xdd66);
    // dprintf(1, "\n");
	// dprintf(1, "vrai : |toto %##.0xet %#.X%###.1x|\n", 0, 0, 0);
	// ft_printf("faux : |toto %##.0xet %#.X%###.1x|\n", 0, 0, 0);
    // dprintf(1, "\n");




			// dprintf(1, "\n");
			// ft_printf("	#87	ret    '%d' \n", ft_printf("'%s'", "basique"));
			// // ft_printf("	#88	ret    '%d' \n", ft_printf("'%10s'", NULL));
			// // ft_printf("	#89	ret    '%d' \n", ft_printf("'%2s'", NULL));
			// // ft_printf("	#90	ret    '%d' \n", ft_printf("'%-2s'", NULL));
			// // ft_printf("	#91	ret    '%d' \n", ft_printf("'%10.2s'", NULL));
			// // ft_printf("	#92	ret    '%d' \n", ft_printf("'%-10s'", NULL));
			// // ft_printf("	#93	ret    '%d' \n", ft_printf("'%-10.5s'", NULL));
			// // ft_printf("	#94	ret    '%d' \n", ft_printf("'%-15s'", "basique"));
			// dprintf(1, "\n");
			// printf("\n");
			// printf("	#87	ret    '%d' \n", printf("'%s'", "basique"));
			// // printf("	#88	ret    '%d' \n", printf("'%10s'", NULL));
			// // printf("	#89	ret    '%d' \n", printf("'%2s'", NULL));
			// // printf("	#90	ret    '%d' \n", printf("'%-2s'", NULL));
			// // printf("	#91	ret    '%d' \n", printf("'%10.2s'", NULL));
			// // printf("	#92	ret    '%d' \n", printf("'%-10s'", NULL));
			// // printf("	#93	ret    '%d' \n", printf("'%-10.5s'", NULL));
			// // printf("	#94	ret    '%d' \n", printf("'%-15s'", "basique"));
			// printf("\n");
    return (0);
}